all:
	#python3 generate_neo_test_cases.py 3136 576 64 > neo_resnet50_2.h
	#python3 generate_neo_test_cases.py 256 768  768   > neo_bert_1.h
	#python3 generate_neo_test_cases.py 256 3072 768   > neo_bert_2.h
	#python3 generate_neo_test_cases.py 256 768 3072   > neo_bert_3.h
	#python3 generate_neo_test_cases.py 512 1024 1024  > neo_dlrm_1.h
	#python3 generate_neo_test_cases.py 512 1024 64    > neo_dlrm_2.h
	#python3 generate_neo_test_cases.py 512 2048 2048  > neo_dlrm_3.h
	python3 generate_neo_test_cases.py 8 128 128 > ../neo_resnet50_2.c
